In [1]:
import numpy as np

In [3]:
a = np.random.rand(5)  # 배열 a 에 랜덤한 5개의 가우스 변수 생성
print(a)
print(a.shape)    # 1순위 배열, 행 벡터 & 열 벡터 그 무엇도 아님

[0.499023   0.57329804 0.61915925 0.81866615 0.24248752]
(5,)


In [4]:
print(a.T)  # 행렬을 전치 햇는대 차이가 없음!

[0.499023   0.57329804 0.61915925 0.81866615 0.24248752]


In [6]:
print(np.dot(a, a.T))

1.6900672288687726


In [8]:
a = np.random.randn(5, 1)
print(a)
print(a.T)   # 전치가 성공적으로 수행됨
print(a.shape)

[[0.683695  ]
 [1.6865269 ]
 [0.54654868]
 [1.87070777]
 [0.35854393]]
[[0.683695   1.6865269  0.54654868 1.87070777 0.35854393]]
(5, 1)


In [10]:
print(np.dot(a, a.T))

[[0.46743885 1.15307001 0.3736726  1.27899354 0.24513469]
 [1.15307001 2.84437298 0.92176906 3.15499897 0.60469398]
 [0.3736726  0.92176906 0.29871546 1.02243287 0.19596171]
 [1.27899354 3.15499897 1.02243287 3.49954754 0.67073091]
 [0.24513469 0.60469398 0.19596171 0.67073091 0.12855375]]


In [13]:
assert(a.shape==(5, 1))