In [4]:
import numpy as np

In [20]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [21]:
cal = A.sum(axis=0)  # axis=0: 수직으로 합산
print(cal)

[ 59.  239.  155.4  76.9]


In [28]:
percentage = 100*A/cal.reshape(1, 4) 
print(percentage)
# reshape 명령어가 없어도 이미 (1, 4) 행렬이지만 행렬의 치수가 올바른지 확인하기 위해 호출하는 경우가 많다(성능 영향 거의 없음)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
